### ISSUE TITLE
swagger missing path ID annotation

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Consultations#57]
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/214608/162192147-92f6d38b-e1c3-4f4c-b14b-2fb9c38f26da.png">
missing path ID annotation

**Comment by HerbertIV** [comment]
![image](https://user-images.githubusercontent.com/62691459/163555070-44376ef4-f2ef-4204-b25b-5ae847577592.png)

Close
